[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
futures = "0.3"
async-std = { version = "1.12.0", features = ["attributes"] }
async-trait = "0.1.74"
